// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load .env.development hoặc .env.production dựa trên NODE_ENV
const nodeEnv = process.env.NODE_ENV || "development";
config({ path: `.env.${nodeEnv}` });

// Tạo DATABASE_URL từ các biến DB_* nếu chưa có
function getDatabaseUrl(): string {
  // Nếu đã có DATABASE_URL, dùng nó
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }

  // Tự động tạo từ DB_HOST, DB_USERNAME, DB_PASSWORD, DB_NAME, DB_PORT
  const dbHost = process.env.DB_HOST;
  const dbPort = process.env.DB_PORT || "3306";
  const dbUserName = process.env.DB_USERNAME;
  const dbPassWord = process.env.DB_PASSWORD;
  const dbName = process.env.DB_NAME;

  if (dbHost && dbUserName && dbPassWord && dbName) {
    return `mysql://${dbUserName}:${dbPassWord}@${dbHost}:${dbPort}/${dbName}`;
  }

  throw new Error(
    "DATABASE_URL is not set and cannot be generated from DB_* variables. " +
    "Please set DATABASE_URL in .env.development or provide DB_HOST, DB_USERNAME, DB_PASSWORD, DB_NAME"
  );
}

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
